/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Openbox Window Preferences");
gchar *s = N_("<span weight=\"bold\">Theme</span>");
gchar *s = N_("    ");
gchar *s = N_("Theme");
gchar *s = N_("<span weight=\"bold\">Windows</span>");
gchar *s = N_("    ");
gchar *s = N_("_Windows retain a border when undecorated");
gchar *s = N_("<span weight=\"bold\">Window Titles</span>");
gchar *s = N_("    ");
gchar *s = N_("_Button order:");
gchar *s = N_("N - The window's icon\n"
              "D - The all-desktops (sticky) button\n"
              "S - The shade (roll up) button\n"
              "L - The label (window title)\n"
              "I - The iconify (minimize) button\n"
              "M - The maximize button\n"
              "C - The close button");
gchar *s = N_("<span weight=\"bold\">Fonts</span>");
gchar *s = N_("    ");
gchar *s = N_("_Active window title: ");
gchar *s = N_("_Inactive window title: ");
gchar *s = N_("Menu _header: ");
gchar *s = N_("_Menu Item: ");
gchar *s = N_("_On-screen display: ");
gchar *s = N_("Appearance");
gchar *s = N_("<span weight=\"bold\">Focusing Windows</span>");
gchar *s = N_("    ");
gchar *s = N_("Focus windows when the _mouse pointer moves over them");
gchar *s = N_("    ");
gchar *s = N_("_Raise windows when the mouse pointer moves over them");
gchar *s = N_("_Delay before focusing and raising windows:");
gchar *s = N_("ms");
gchar *s = N_("_Give focus to the last used window, instead of under the mouse");
gchar *s = N_("Focus _new windows when they appear");
gchar *s = N_("<span weight=\"bold\">Placing Windows</span>");
gchar *s = N_("    ");
gchar *s = N_("_Place new windows under the mouse pointer");
gchar *s = N_("<span weight=\"bold\">Moving and Resizing Windows</span>");
gchar *s = N_("    ");
gchar *s = N_("Update the window c_ontents while resizing");
gchar *s = N_("Amount of resistance against other _windows:");
gchar *s = N_("px");
gchar *s = N_("Amount of resistance against screen _edges:");
gchar *s = N_("px");
gchar *s = N_("Behavior");
gchar *s = N_("<span weight=\"bold\">Desktops</span>");
gchar *s = N_("    ");
gchar *s = N_("_Number of desktops: ");
gchar *s = N_("_Desktop names:");
gchar *s = N_("Desktops");
gchar *s = N_("<span weight=\"bold\">Position</span>");
gchar *s = N_("    ");
gchar *s = N_("_Position:");
gchar *s = N_("Top Left");
gchar *s = N_("Top");
gchar *s = N_("Top Right");
gchar *s = N_("Left");
gchar *s = N_("Right");
gchar *s = N_("Bottom Left");
gchar *s = N_("Bottom");
gchar *s = N_("Bottom Right");
gchar *s = N_("Floating");
gchar *s = N_("    ");
gchar *s = N_("_Floating position:");
gchar *s = N_("x");
gchar *s = N_("_Orientation: ");
gchar *s = N_("Vertical");
gchar *s = N_("Horizontal");
gchar *s = N_("<span weight=\"bold\">Stacking</span>");
gchar *s = N_("    ");
gchar *s = N_("Keep dock _above other windows");
gchar *s = N_("A_llow dock to be both above and below windows");
gchar *s = N_("Keep dock _below other windows");
gchar *s = N_("<span weight=\"bold\">Hiding</span>");
gchar *s = N_("    ");
gchar *s = N_("_Hide off screen");
gchar *s = N_("    ");
gchar *s = N_("_Delay before hiding:");
gchar *s = N_("ms");
gchar *s = N_("Dock");
gchar *s = N_("About");
gchar *s = N_("About ObConf");
gchar *s = N_("<span weight=\"bold\" size=\"xx-large\">ObConf 3.0</span>");
gchar *s = N_("A preferences manager for Openbox");
gchar *s = N_("Copyright (c) 2003-2006\n"
              "Dana Jansens <danakj@orodu.net>\n"
              "Tim Riley <tr@slackzone.org>");
